### PR TITLE
Adding gzip to all endpoints

### PR DESCRIPTION
**Pull request by ramanxg**
I installed the package `compression` and have added it as middleware. 

Note: I used the third fastest level of compression based on the docs here: https://www.npmjs.com/package/compression. Upon testing, when using compression, download times are extremely low, but the TTFB (time to first byte, or until response from server), is higher. Compared to the default level compression will be faster, but downloads will take a little longer. Since TTFB is much longer, I went for faster compression to reduce that over download times.

### CODE REVIEW

**Comment by ChaseC99** [comment]
This is awesome how it improves the response time of our larger requests! 

But I'm kind of concerned about how it affects our smaller requests..... For example, a simple instructor query like:
```
instructor(ucinetid: "pattis") {
    name
    shortened_name 
}
```
the response time goes from 5.68ms (3.72 TTFB + 0.46 download) to 92.52ms (88.93 TTFB + 0.46 download). That's like 18x longer than before. 

Maybe there's a way for us to only gzip responses over a certain size? If not idk how we should judge this tradeoff....

**Comment by ramanxg** [comment]
So there is, https://www.npmjs.com/package/compression#threshold. The default threshold is 1kb, but not exactly sure what a good threshold is. Right now, I was thinking 128kb, but I am not super sure. gonna play around with it.

**Comment by ramanxg** [comment]
The deployment was not meant to happen, reverting to master.

**Comment by ramanxg** [comment]
My guess is 128 kb is actually not bad. I think we should go with that. Further along, we can adjust this number.

**Review by ChaseC99 — APPROVED** [review]
Threshold seems reasonable! Let's try it out 👍🏼

**Pull request merged**
