### PR TITLE
Github CI

### PR DESCRIPTION
**Pull request by nananananate**
A simple workflow using Github Actions to run unit tests on every push and pull request to `master` .

## Changes made

Besides creating the workflow itself, I did make a major change to the structure of our application which should be reviewed. 

### Separation of Server and App

I've separated `app.js` into two files: `server.js` and `app.js`. `server.js` is quite small and only deals with running the actual server, while `app.js` contains all the routes. 

This started as the best solution for improper testing teardown -- jtest was having issues closing the server. After reading more about the solution, it seems there are some developers advocating for this separation for the sake of modularity:

* [GeekForGeeks](https://www.geeksforgeeks.org/why-express-app-and-server-files-kept-separately/)
* [Node best practices](https://github.com/goldbergyoni/nodebestpractices#-14-separate-express-app-and-server)

The biggest thing about this is **running the server has changed**.

```
npm start server.js
```

If this is problematic, please let me know! You'll have to change this on Heroku on the next redeploy. 

## Next steps

Before moving onto other tasks, I'd like to look into code quality scanning and coverage. I'll look into CircleCI for implementing this in a pipeline. 

@ramanxg do you think you can enable CircleCI for the repo?

### CODE REVIEW

**Comment by ramanxg** [comment]
I think I enabled CircleCI on the repo, but I'm not sure. Can you just double check?

**Comment by nananananate** [comment]
Looks like it's still disabled at the repository level.... Not sure why this keeps happening:

image

Double check [here](https://app.circleci.com/projects/project-dashboard/github/icssc-projects/)

**Comment by nananananate** [comment]
I added a test configuration file for CircleCI, as per their [tutorial](https://circleci.com/docs/2.0/config-intro/). So once CircleCI is allowed, CircleCI should detect it on the next push.

**Review by ramanxg — APPROVED** [review]
Looks good! Once we deploy the branch, I can update the heroku command.

**Comment by ramanxg** [comment]
Also, it looks like the CircleCI works! If you can't see it, then it might be some permissions I need to give you on github.

image

**Pull request merged**
