### PR TITLE
Added Course Level Division Filter to Grades Queries

### LINKED ISSUE #131: Add filter for UpperDiv and LowerDiv classes for grades.
Add a filter for Upperdiv and LowerDiv to exclude these classes. 

UpperDiv classes are greater than or equal to 100. LowerDiv classes are less than 100. Current number is stored as a string, and might require adding a column to the database with only the number. For example classes like ICS 139W, would need the W removed so it's considered a number and not a character.

### PR DESCRIPTION
**Pull request by ramanxg**
## Reference Issues
Closes #131 and #123

## Summary of Change/Fix 
Created a course level division parameter, so you can filter grades data by lower and upper division classes.

Adds a field for `number_int` for the integer of the course number to the grades db. This number is then used to check if a course in our db is lower division (less than 100), or upper division (between 100 and 199). 

Added descriptions to the graphql playgound for grades, so they can see these in the playground, and what types of inputs they need. Also changed in grades.md, to now be `Exclude P/NP Only courses`.

Added unit tests to check that this feature is working.

## Test Plan
Run `npm test`

Test out these queries in GraphQL:

Check that the course numbers for this are all less than 100. 
```
{
  grades (year:"2020-21", department:"I&C SCI", division:"LowerDiv") {
		grade_distributions {
      course_offering {
        year
        quarter
        course {
            department
            number
            title
        }
      }
    }
  }
}
```

Check that the course numbers for this are all greater than or equal to 100 and less than 200.
```
{
  grades (year:"2020-21", department:"I&C SCI", division:"UpperDiv") {
		grade_distributions {
      course_offering {
        year
        quarter
        course {
            department
            number
            title
        }
      }
    }
  }
}
```

Verify this endpoint also has only lower div classes:
http://localhost:8000/rest/v0/grades/raw?term=2020%20Fall&department=I%26C%20SCI&division=lowerdiv

Verify this has only upper div:
http://localhost:8000/rest/v0/grades/raw?term=2020%20Fall&department=I%26C%20SCI&division=upperdiv

### CODE REVIEW

**Comment by ileenf** [comment]
Not sure if this is on my end, but when I try to verify the endpoints I reach an error.
Screen Shot 2022-01-22 at 12 48 26 PM

**Comment by ramanxg** [comment]
> All the testcases pass! However not sure if this is on my end, but when I try to verify the endpoints I reach an error.
> 
> Screen Shot 2022-01-22 at 12 48 26 PM

Try running this with `npm start` instead of `mkdocs serve` (since this only serves documentation). Then if you want to see the docs in the full api, you can build them with `mkdocs build -d docs-site`

**Comment by ileenf** [comment]
When checking the lower div classes endpoint, I noticed some classes had numbers greater than 100, such as ICS 193 and ICS 139W.
Screen Shot 2022-01-25 at 1 07 22 AM

Additionally, the upper div classes endpoint contains mostly lower div classes.

**Comment by ramanxg** [comment]
> When checking the lower div classes endpoint, I noticed some classes had numbers greater than 100, such as ICS 193 and ICS 139W. Screen Shot 2022-01-25 at 1 07 22 AM
> 
> Additionally, the upper div classes endpoint contains mostly lower div classes.

I was checking myself, and all of mine are completely lowerdiv. 

image

Can you retry fetching the latest commit. I had to update the database, because of some conflicts with master.

**Comment by ileenf** [comment]
My bad, i didn't switch to this branch. It looks like everything is good now.

**Review by ileenf — COMMENTED** [review]
Looks good.

**Review by ileenf — APPROVED** [review]
Looks good!

**Pull request merged**
