### PR TITLE
fix graphql docs

### PR DESCRIPTION
**Pull request by ileenf**
## Reference Issues
#129 

## Summary of Change/Fix 
Added closing ticks to the learn-more example query 1 to fix graphql docs.

## Testing Plan
Tested by comparing differences with other query examples. Made sure output was the same on the local workspace.

Before: 
Screen Shot 2022-01-18 at 5 53 06 PM

After: 
Screen Shot 2022-01-18 at 5 53 25 PM

### CODE REVIEW

**Comment by ramanxg** [comment]
Good stuff! A few things: 

- If you could show a screenshot of what you fixed in the documentation, i.e. before/after. 
- Explain how you tested it, so I can follow that and test it as well.
- Add to the `.gitignore`, the `.idea/` folder to prevent these from being committed. 
  - https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

**Comment by ileenf** [comment]
ok fixed! let me know if there's anything else I should change or add.

**Comment by ramanxg** [comment]
> * Add to the `.gitignore`, the `.idea/` folder to prevent these from being committed.

Make sure you add this! We don't want these folders in our git repo!

**Comment by ileenf** [comment]
My bad, I misinterpreted that line. It should be fixed now!

**Review by ramanxg — APPROVED** [review]
Awesome first PR!

I added a change because I realized my setup workspace documentation was not entirely correct.

**Pull request merged**
